
id = "FishyTracker"
name = "Fishy Tracker"
description = "Track caught sizes and qualities for every fish!"
version = "1.1.0"
homepage = "https://github.com/puppy-girl/FishyTracker"
author = "Jade"

icon = "icon.png"
readme = "README.md"

[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
